### ISSUE TITLE
Can't run with java visualVM options

### ISSUE THREAD

**Issue by dieforrockvn** [danthegoodman/gradle-capsule-plugin#22]
Hi,
I try to run capsule jar file with visualVM options but always get
"Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 1111; nested exception is: 
	java.net.BindException: Address already in use"
 
java cmd:
java -Xms1G -Xmx4G -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=1111 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -jar MainService.jar

If I build the jar file using Eclipse (export tool, not gradle), I can run this command without errors.
Thanks.

**Comment by pron** [comment]
This is a Capsule issue, unrelated to the Gradle plugin. The reason is that any command line argument is passed to both the capsule launcher process and the application, and in this case, they would both try to use the same port.

The solution is to use the `-Dcapsule.jvm.args` flag so:

    java -Dcapsule.jvm.args='-Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=1111...'

A few general notes, however. 

1. To run VisualVM you don't need any of those options if you're connecting locally. VisualVM would automatically detect your process and attach to it. If you do want to provide remote access, always enable authentication. As it stands, you're now allowing anyone to control your app remotely.

2. There shouldn't be a need to specify min and max heap sizes on the command line. The whole idea of Capsule is that you can specify those in the manifest. The command line should only be used (rarely) to *override* the manifest settings.

**Comment by dieforrockvn** [comment]
Your solution works. Save my day.
Thanks.
